default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: postgres

development:
  <<: *default
  database: server_v1

test:
  <<: *default
  database: server_v1_test

production:
  <<: *default
  database: server_v1_production